name: Java CI with JUnit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Compile code
      run: javac -cp .:src $(find src -name "*.java")

    - name: Run JUnit tests
      run: |
        mkdir -p test-reports
        java -cp .:src:$(find ~/.m2 -name 'junit-4*.jar' | head -n1) org.junit.runner.JUnitCore com.ontrack.TaskServiceTest || true
